from django.urls import path

from .views import (
    AnnouncementListCreateView,
    BroadcastView,
    ConversationDetailView,
    ConversationListView,
    FAQListView,
    InvitationCreateView,
    InvitationDetailView,
    InvitationMineView,
    InvitationRespondView,
    NotificationDeleteView,
    NotificationListView,
    NotificationReadAllView,
    NotificationReadView,
    NotificationUnreadCountView,
    ReportListCreateView,
    ReportStatusView,
    SupportTicketDetailView,
    SupportTicketListCreateView,
    SupportInfoView,
)

urlpatterns = [
    path("notifications/", NotificationListView.as_view(), name="notification-list"),
    path("notifications/unread-count/", NotificationUnreadCountView.as_view(), name="notification-unread-count"),
    path("notifications/read-all/", NotificationReadAllView.as_view(), name="notification-read-all"),
    path("notifications/<int:pk>/read/", NotificationReadView.as_view(), name="notification-read"),
    path("notifications/<int:pk>/", NotificationDeleteView.as_view(), name="notification-delete"),
    path("broadcast/", BroadcastView.as_view(), name="broadcast"),
    path("conversations/mine/", ConversationListView.as_view(), name="conversation-list"),
    path("conversations/", ConversationListView.as_view(), name="conversation-create"),
    path("conversations/<int:pk>/", ConversationDetailView.as_view(), name="conversation-detail"),
    path("announcements/", AnnouncementListCreateView.as_view(), name="announcement-create"),
    path("announcements/event/<int:event_id>/", AnnouncementListCreateView.as_view(), name="announcement-list"),
    path("invitations/", InvitationCreateView.as_view(), name="invitation-create"),
    path("invitations/mine/", InvitationMineView.as_view(), name="invitation-mine"),
    path("invitations/<str:token>/", InvitationDetailView.as_view(), name="invitation-detail"),
    path("invitations/<str:token>/<str:action>/", InvitationRespondView.as_view(), name="invitation-respond"),
    path("support/", SupportTicketListCreateView.as_view(), name="support-list-create"),
    path("support/<int:pk>/", SupportTicketDetailView.as_view(), name="support-detail"),
    path("support-info/", SupportInfoView.as_view(), name="support-info"),
    path("faqs/", FAQListView.as_view(), name="faq-list"),
    path("reports/", ReportListCreateView.as_view(), name="report-list-create"),
    path("reports/<int:pk>/status/", ReportStatusView.as_view(), name="report-status"),
]
